name: Android CI
on:
  workflow_dispatch:
  workflow_call:

env:
  HAXE_VERSION: 4.3.7

jobs:
  android:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib git hxcpp https://github.com/th2l-devs/hxcpp --quiet
          haxelib install format --quiet
          haxelib install hxp --quiet
      - name: Enable HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV
      - name: Configure Lime
        run: |
          haxelib dev lime ${{ github.workspace }}
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME -nocffi
          haxelib run lime config ANDROID_SETUP true -nocffi
      - name: Rebuild Lime
        run: |
          haxelib run lime rebuild android -release -nocolor -nocffi -ONLY_ARMV7
          haxelib run lime rebuild android -release -nocolor -nocffi -ONLY_ARM64
          haxelib run lime rebuild android -release -nocolor -nocffi -ONLY_X86
          haxelib run lime rebuild android -release -nocolor -nocffi -ONLY_X86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-NDLL
          path: |
            ndll/Android/
            !**/.gitignore
            lime.png
          if-no-files-found: error
